// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa-lxOyIdBx6CcuzC24shmvxoZ7qPcl98',
    appId: '1:707544485105:web:9bbdb4d82d3f05d281ed50',
    messagingSenderId: '707544485105',
    projectId: 'chat-c7c82',
    authDomain: 'chat-c7c82.firebaseapp.com',
    databaseURL: 'https://chat-c7c82-default-rtdb.firebaseio.com',
    storageBucket: 'chat-c7c82.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDknY06fH1KF7Llfk-XGpMMAdZZscRrZXM',
    appId: '1:707544485105:android:b629c1b92814638481ed50',
    messagingSenderId: '707544485105',
    projectId: 'chat-c7c82',
    databaseURL: 'https://chat-c7c82-default-rtdb.firebaseio.com',
    storageBucket: 'chat-c7c82.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmP_DYKx9-8FlPrede3y8bQAtzN_kNB78',
    appId: '1:707544485105:ios:91713ecec038f4e681ed50',
    messagingSenderId: '707544485105',
    projectId: 'chat-c7c82',
    databaseURL: 'https://chat-c7c82-default-rtdb.firebaseio.com',
    storageBucket: 'chat-c7c82.appspot.com',
    iosClientId: '707544485105-rreb2q2hko17e88n1nmhlnk9dcemjddh.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmP_DYKx9-8FlPrede3y8bQAtzN_kNB78',
    appId: '1:707544485105:ios:11a99fff9558906f81ed50',
    messagingSenderId: '707544485105',
    projectId: 'chat-c7c82',
    databaseURL: 'https://chat-c7c82-default-rtdb.firebaseio.com',
    storageBucket: 'chat-c7c82.appspot.com',
    iosClientId: '707544485105-21t67s7s8agkio5sb2hut8elm1l53db2.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat.RunnerTests',
  );
}
